name: job_timer
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  asuka: ^2.0.0+1
  bloc: ^8.0.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter_modular: ^5.0.3
  fl_chart: ^0.51.0
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  flutter_bloc: ^8.0.1
  google_sign_in: ^5.3.3
  modular_bloc_bind: ^1.0.1
  validatorless: ^1.2.1
  isar: ^3.0.0-dev.0
  isar_flutter_libs: ^3.0.0-dev.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.0.0-dev.0
  build_runner: ^2.1.11

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: JobTimerIcons
      fonts:
        - asset: assets/fonts/JobTimerIcons.ttf