// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCutUAXvyKr3dPRxUrMw8i3lYmoefHAmJY',
    appId: '1:392858769973:web:6c7f0ca374b3a85961af7c',
    messagingSenderId: '392858769973',
    projectId: 'job-timer-android',
    authDomain: 'job-timer-android.firebaseapp.com',
    storageBucket: 'job-timer-android.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH_jAjwrOLDlfvWJExf9wvn7PKCSWFunI',
    appId: '1:392858769973:android:7ea4e76d5d58963b61af7c',
    messagingSenderId: '392858769973',
    projectId: 'job-timer-android',
    storageBucket: 'job-timer-android.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJkLjlEzu_sWgjYDGtSh9EfS9Be0jhq9s',
    appId: '1:392858769973:ios:e06bfe39a7c1f29461af7c',
    messagingSenderId: '392858769973',
    projectId: 'job-timer-android',
    storageBucket: 'job-timer-android.appspot.com',
    iosClientId: '392858769973-d6pcfd5nqblsvsenfvf4jb3m4qet4jpn.apps.googleusercontent.com',
    iosBundleId: 'br.com.souza.richard.jobTimer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJkLjlEzu_sWgjYDGtSh9EfS9Be0jhq9s',
    appId: '1:392858769973:ios:e06bfe39a7c1f29461af7c',
    messagingSenderId: '392858769973',
    projectId: 'job-timer-android',
    storageBucket: 'job-timer-android.appspot.com',
    iosClientId: '392858769973-d6pcfd5nqblsvsenfvf4jb3m4qet4jpn.apps.googleusercontent.com',
    iosBundleId: 'br.com.souza.richard.jobTimer',
  );
}
